"""trash, experience

Revision ID: 1072f07d761f
Revises: 8fd912af413
Create Date: 2014-12-07 17:46:39.484893

"""

# revision identifiers, used by Alembic.
revision = '1072f07d761f'
down_revision = '8fd912af413'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('trash', sa.Boolean(), nullable=True))
    op.add_column('service_provider', sa.Column('experience', sa.Float(), nullable=True))
    op.add_column('service_provider', sa.Column('trash', sa.Boolean(), nullable=True))
    op.add_column('service_skill', sa.Column('trash', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_skill', 'trash')
    op.drop_column('service_provider', 'trash')
    op.drop_column('service_provider', 'experience')
    op.drop_column('service', 'trash')
    ### end Alembic commands ###
