"""empty message

Revision ID: 10b3162f8cc6
Revises: 2fba9490b1f4
Create Date: 2015-03-04 22:37:31.832030

"""

# revision identifiers, used by Alembic.
revision = '10b3162f8cc6'
down_revision = '2fba9490b1f4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_provider_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_provider_id', sa.Integer(), nullable=True),
    sa.Column('service_skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_provider_id'], ['service_provider.id'], ),
    sa.ForeignKeyConstraint(['service_skill_id'], ['service_skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_provider_skill')
    ### end Alembic commands ###
