"""service provider details

Revision ID: 1dba51972bd2
Revises: 50ee9968b479
Create Date: 2015-04-09 01:15:45.905795

"""

# revision identifiers, used by Alembic.
revision = '1dba51972bd2'
down_revision = '50ee9968b479'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_provider', sa.Column('details', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_provider', 'details')
    ### end Alembic commands ###
