"""adding gcm registration id

Revision ID: 2246edda326c
Revises: 4c4fbe19bc20
Create Date: 2014-12-15 23:49:04.562338

"""

# revision identifiers, used by Alembic.
revision = '2246edda326c'
down_revision = '4c4fbe19bc20'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_provider', sa.Column('gcm_reg_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_provider', 'gcm_reg_id')
    ### end Alembic commands ###
