"""empty message

Revision ID: 22912ce35357
Revises: 41f51a64574c
Create Date: 2014-12-07 00:20:14.650717

"""

# revision identifiers, used by Alembic.
revision = '22912ce35357'
down_revision = '41f51a64574c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_provider', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('service_provider', sa.Column('service', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service_provider', 'service', ['service'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_provider', type_='foreignkey')
    op.drop_column('service_provider', 'service')
    op.drop_column('service_provider', 'cost')
    ### end Alembic commands ###
