"""removing service for service provider

Revision ID: 28161fcf0f3e
Revises: e63d269d8c4
Create Date: 2014-12-21 15:45:16.359211

"""

# revision identifiers, used by Alembic.
revision = '28161fcf0f3e'
down_revision = 'e63d269d8c4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'service_provider_service_fkey', 'service_provider', type_='foreignkey')
    op.drop_column('service_provider', 'service')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_provider', sa.Column('service', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'service_provider_service_fkey', 'service_provider', 'service', ['service'], ['id'])
    ### end Alembic commands ###
