"""empty message

Revision ID: 3609a703337f
Revises: 15c9834e0b4f
Create Date: 2015-01-20 00:58:30.095190

"""

# revision identifiers, used by Alembic.
revision = '3609a703337f'
down_revision = '15c9834e0b4f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signupemail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('trash', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signupemail')
    ### end Alembic commands ###
