"""sp, user changes

Revision ID: 3b4890df160d
Revises: 28161fcf0f3e
Create Date: 2015-01-07 02:09:20.555497

"""

# revision identifiers, used by Alembic.
revision = '3b4890df160d'
down_revision = '28161fcf0f3e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_provider', sa.Column('email', sa.String(length=256), nullable=False))
    op.drop_column('user', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('service_provider', 'email')
    ### end Alembic commands ###
