"""empty message

Revision ID: 41f51a64574c
Revises: 4857f6e66f2e
Create Date: 2014-12-07 00:04:16.899422

"""

# revision identifiers, used by Alembic.
revision = '41f51a64574c'
down_revision = '4857f6e66f2e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Column, Integer, String, Boolean, Float

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('skills', postgresql.ARRAY(String()), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=2048), nullable=False),
    sa.Column('home_location', postgresql.ARRAY(Float()), nullable=False),
    sa.Column('office_location', postgresql.ARRAY(Float()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    op.drop_table('service_provider')
    ### end Alembic commands ###
