"""order revision

Revision ID: 45a2f632b3b9
Revises: 555911ef1f34
Create Date: 2015-04-05 20:43:42.013841

"""

# revision identifiers, used by Alembic.
revision = '45a2f632b3b9'
down_revision = '555911ef1f34'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sp_rating', sa.Integer(), nullable=True),
    sa.Column('su_rating', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_rating')
    ### end Alembic commands ###
