"""adding verify flag to sp

Revision ID: 466c62396372
Revises: 492db63cb020
Create Date: 2014-12-13 23:30:57.863735

"""

# revision identifiers, used by Alembic.
revision = '466c62396372'
down_revision = '492db63cb020'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_provider', sa.Column('verified', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_provider', 'verified')
    ### end Alembic commands ###
