"""adding job address

Revision ID: 492db63cb020
Revises: a30be6eda6a
Create Date: 2014-12-13 22:35:24.389644

"""

# revision identifiers, used by Alembic.
revision = '492db63cb020'
down_revision = 'a30be6eda6a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('address', sa.String(length=2048), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'address')
    ### end Alembic commands ###
