"""adding phone number to job

Revision ID: 4c4fbe19bc20
Revises: 20f95f51fbf4
Create Date: 2014-12-14 18:37:38.107226

"""

# revision identifiers, used by Alembic.
revision = '4c4fbe19bc20'
down_revision = '20f95f51fbf4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('phone_number', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'phone_number')
    ### end Alembic commands ###
