"""empty message

Revision ID: 555911ef1f34
Revises: 2093179e414b
Create Date: 2015-04-05 19:05:39.656613

"""

# revision identifiers, used by Alembic.
revision = '555911ef1f34'
down_revision = '2093179e414b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missedorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missedorders')
    ### end Alembic commands ###
