"""sp created

Revision ID: 574514831e8d
Revises: e488779bbe0
Create Date: 2015-04-11 15:53:05.254170

"""

# revision identifiers, used by Alembic.
revision = '574514831e8d'
down_revision = 'e488779bbe0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_provider', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_provider', 'created')
    ### end Alembic commands ###
