"""removing not null constraint

Revision ID: 5f691302544
Revises: 45079e4d0040
Create Date: 2014-12-10 22:28:30.783691

"""

# revision identifiers, used by Alembic.
revision = '5f691302544'
down_revision = '45079e4d0040'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_provider', 'address',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    op.alter_column('service_provider', 'home_location',
               existing_type=postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)),
               nullable=True)
    op.alter_column('service_provider', 'office_location',
               existing_type=postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)),
               nullable=True)
    op.alter_column('service_provider', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_provider', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('service_provider', 'office_location',
               existing_type=postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)),
               nullable=False)
    op.alter_column('service_provider', 'home_location',
               existing_type=postgresql.ARRAY(postgresql.DOUBLE_PRECISION(precision=53)),
               nullable=False)
    op.alter_column('service_provider', 'address',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    ### end Alembic commands ###
