"""initial

Revision ID: 8fd912af413
Revises: 
Create Date: 2014-12-07 01:48:28.517299

"""

# revision identifiers, used by Alembic.
revision = '8fd912af413'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=2048), nullable=False),
    sa.Column('home_location', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('office_location', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('service', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('inspection', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider'], ['service_provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_skill')
    op.drop_table('service_provider')
    op.drop_table('service')
    ### end Alembic commands ###
