"""empty message

Revision ID: 9cc96c394e6
Revises: 4991625194b6
Create Date: 2015-03-05 22:59:20.640771

"""

# revision identifiers, used by Alembic.
revision = '9cc96c394e6'
down_revision = '4991625194b6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_provider', sa.Column('day_end', sa.Integer(), nullable=True))
    op.add_column('service_provider', sa.Column('day_start', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_provider', 'day_start')
    op.drop_column('service_provider', 'day_end')
    ### end Alembic commands ###
