"""skills

Revision ID: e488779bbe0
Revises: 1dba51972bd2
Create Date: 2015-04-11 03:04:45.125457

"""

# revision identifiers, used by Alembic.
revision = 'e488779bbe0'
down_revision = '1dba51972bd2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('service', sa.String(length=64), nullable=True))
    op.drop_constraint(u'job_service_id_fkey', 'job', type_='foreignkey')
    op.drop_column('job', 'service_id')
    op.drop_table('service_provider_service')
    op.drop_table('service_provider_skill')
    op.drop_table('service_skill')
    op.drop_table('service')
    op.add_column('service_provider', sa.Column('skills', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_provider', 'skills')
    op.add_column('job', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'job_service_id_fkey', 'job', 'service', ['service_id'], ['id'])
    op.drop_column('job', 'service')
    op.create_table('service_provider_skill',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service_provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_skill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trash', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_provider_id'], [u'service_provider.id'], name=u'service_provider_skill_service_provider_id_fkey'),
    sa.ForeignKeyConstraint(['service_skill_id'], [u'service_skill.id'], name=u'service_provider_skill_service_skill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'service_provider_skill_pkey')
    )
    op.create_table('service_skill',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('inspection', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trash', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], name=u'service_skill_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'service_skill_pkey')
    )
    op.create_table('service_provider_service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trash', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], name=u'service_provider_service_service_id_fkey'),
    sa.ForeignKeyConstraint(['service_provider_id'], [u'service_provider.id'], name=u'service_provider_service_service_provider_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'service_provider_service_pkey')
    )
    op.create_table('service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('trash', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'service_pkey')
    )
    ### end Alembic commands ###
