"""service provider range

Revision ID: e63d269d8c4
Revises: 2246edda326c
Create Date: 2014-12-21 14:58:31.019770

"""

# revision identifiers, used by Alembic.
revision = 'e63d269d8c4'
down_revision = '2246edda326c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_provider', sa.Column('service_range', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_provider', 'service_range')
    ### end Alembic commands ###
